---
title: "Using_ChemLogic"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using_ChemLogic}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ChemLogic)
```


```{r loading_binary_data}
AR_data <- load_chem_data(path = "inst/extdata/Curated_AR_TOX21.xlsx", 
                          file_type = "xlsx", 
                          filter = TRUE, 
                          filter_type = "Pubchem")

ER_data <- load_chem_data(path = "inst/extdata/Curated_ER_TOX21.xlsx", 
                          file_type = "xlsx", 
                          filter = TRUE, 
                          filter_type = "Pubchem")

pubchem_fingerprints_cleaned <- load_chem_data(path = "inst/extdata/pubchem_fingerprints_cleaned.txt", 
                                               file_type = "txt", 
                                               filter = FALSE)

PFAS_data <- load_chem_data(path = "inst/extdata/pfas.csv", 
                            file_type = "csv", 
                            filter = TRUE, 
                            filter_type = "Pubchem")
```

```{r loading_outcome_physical_data}

AR_binding_type_data <- load_chem_data(path = "inst/extdata/AR_with_outcome.csv", 
                                       file_type = "csv", 
                                       filter = FALSE)

ER_binding_type_data <- load_chem_data(path = "inst/extdata/ER_with_outcome.csv", 
                                       file_type = "csv", 
                                       filter = FALSE)


AR_rdkit_descriptions <- load_chem_data(path = "inst/extdata/AR_withRDKIT_Descriptors.csv", 
                                        file_type = "csv", 
                                        filter = FALSE)
```

```{r bind_ag_antag_outcomes}

table(AR_data$Name %in% AR_binding_type_data$Name)
AR_cluster_data <- merge(AR_data, AR_binding_type_data, by = "Name")
ER_cluster_data <- merge(ER_data, ER_binding_type_data, by = "Name")


## one of our outcome data variables has blanks for agonists/antagonists, let's change that for better plotting
AR_cluster_data$ASSAY_OUTCOME <- ifelse(AR_cluster_data$ASSAY_OUTCOME =="", "no data", AR_cluster_data$ASSAY_OUTCOME)
AR_cluster_data$ASSAY_OUTCOME <-as.factor(AR_cluster_data$ASSAY_OUTCOME)

table(AR_cluster_data$ASSAY_OUTCOME)
table(ER_cluster_data$ASSAY_OUTCOME)

```

```{r cluster binary molecular features}

AR_cluster_results <- cluster_chem_data(receptor_type = "Androgen", 
                                        data = AR_cluster_data, 
                                        rank = 3, 
                                        filter_type = "Pubchem")

ER_cluster_results <- cluster_chem_data(receptor_type = "Estrogen", 
                                        data = ER_cluster_data, 
                                        rank = 3, 
                                        filter_type = "Pubchem")

AR_cluster_results$kmean_plot
ER_cluster_results$kmean_plot
```



```{r PC plots}

AR_SVD_groups_results <- plot_SVD_kmeans(receptor_type = "Androgen", 
                log_SVD_results = AR_cluster_results$logsvd_results, 
                binary_data = AR_cluster_data, 
                k = 4, 
                endo_ligand = TRUE, 
                endo_ligand_id = '144207887',
                additional_label = TRUE, 
                outcome_label = "ASSAY_OUTCOME") # is the name for testosterone the endogenous ligand

AR_SVD_groups_results$plot_kmeans
AR_SVD_groups_results$plot_outcome_label

AR_data_PCs_grps <- AR_SVD_groups_results$updated_data

ER_SVD_groups_results <- plot_SVD_kmeans(receptor_type = "Estrogen", 
                log_SVD_results = ER_cluster_results$logsvd_results, 
                binary_data = ER_cluster_data, 
                k = 4, 
                endo_ligand = TRUE, 
                endo_ligand_id = '144213948',
                additional_label = TRUE, 
                outcome_label = "ASSAY_OUTCOME") # is the name for testosterone the endogenous ligand

ER_SVD_groups_results$plot_kmeans
ER_SVD_groups_results$plot_outcome_label

ER_data_PCs_grps <- ER_SVD_groups_results$updated_data

AR_data_PCs_grps$log_SVM_group <-as.factor(AR_data_PCs_grps$log_SVM_group)
ER_data_PCs_grps$log_SVM_group <-as.factor(ER_data_PCs_grps$log_SVM_group)

AR_data_PCs_grps$Label_names <- tolower(AR_data_PCs_grps$Label_names)
ER_data_PCs_grps$Label_names <- tolower(ER_data_PCs_grps$Label_names)



```

Running the MCMC logic regression
```{r run logic}
AR_data_PCs_grps$Label_names <- ifelse(AR_data_PCs_grps$Label_names == "inconclusive", "inactive", AR_data_PCs_grps$Label_names)
AR_data_PCs_grps$Label_names <- ifelse(AR_data_PCs_grps$Label_names == "inactive", 0, 1)

table(AR_data_PCs_grps$Label_names)

ER_data_PCs_grps$Label_names <- ifelse(ER_data_PCs_grps$Label_names == "inconclusive", "inactive", ER_data_PCs_grps$Label_names)
ER_data_PCs_grps$Label_names <- ifelse(ER_data_PCs_grps$Label_names == "inactive", 0, 1)


## run the logic MCMC on the androgen receptor data
AR_logic_MCMC_results <- run_logic_MCMC(
  outcome_label = quo(Label_names),
  filter_type = "Pubchem",
  binary_data = AR_data_PCs_grps,
  subgroups = TRUE,
  subgroup_label = quo(log_SVM_group),
  mx_size = 50,
  ntrees = 4,
  n_burn_in = 5000,
  niter = 200000,
  hyperparameters = log(2),
  outcome_permuted = FALSE,
  top_fraction = 0.2
)

## run the logic MCMC on the estrogen receptor data
ER_logic_MCMC_results <- run_logic_MCMC(
  outcome_label = quo(Label_names),
  filter_type = "Pubchem",
  binary_data = ER_data_PCs_grps,
  subgroups = TRUE,
  subgroup_label = quo(log_SVM_group),
  mx_size = 50,
  ntrees = 4,
  n_burn_in = 5000,
  niter = 200000,
  hyperparameters = log(2),
  outcome_permuted = FALSE,
  top_fraction = 0.2
)


```

```{r get MCMC aggregated results}
## collecting results for MCMC logic using all active as positive outcomes vs. non-binding for AR
AR_MCMC_results_main_outcome <- map(.x = AR_logic_MCMC_results[2], 
    .f = collect_logic_MCMC_results, 
    fingerprints = pubchem_fingerprints_cleaned, 
    niter = 200000, 
    fingerprint_idx = 2, 
    binary_data = AR_data_PCs_grps, 
    filter_type = "Pubchem", 
    top_fraction = 0.2)

## collecting results for MCMC logic using all active as positive outcomes vs. non-binding for ER
ER_MCMC_results_main_outcome <- map(.x = ER_logic_MCMC_results[2], 
    .f = collect_logic_MCMC_results, 
    fingerprints = pubchem_fingerprints_cleaned, 
    niter = 200000, 
    fingerprint_idx = 2, 
    binary_data = ER_data_PCs_grps, 
    filter_type = "Pubchem", 
    top_fraction = 0.2)

## collecting results for MCMC logic using subgroups as positive outcomes vs. non-binding
AR_MCMC_results_subgroups <- map(.x = AR_logic_MCMC_results$MCMC_subgroups_analysis, 
    .f = collect_logic_MCMC_results, 
    fingerprints = pubchem_fingerprints_cleaned, 
    niter = 200000, 
    fingerprint_idx = 2, 
    binary_data = AR_data_PCs_grps, 
    filter_type = "Pubchem", 
    top_fraction = 0.2)

ER_MCMC_results_subgroups <- map(.x = ER_logic_MCMC_results$MCMC_subgroups_analysis, 
    .f = collect_logic_MCMC_results, 
    fingerprints = pubchem_fingerprints_cleaned, 
    niter = 200000, 
    fingerprint_idx = 2, 
    binary_data = ER_data_PCs_grps, 
    filter_type = "Pubchem", 
    top_fraction = 0.2)

```

```{r plot_results}
plot_model_size(AR_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, receptor = "Androgen")
plot_model_size(ER_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, receptor = "Estrogen")
```

```{r var_use}
AR_var_use <- plot_variables_in_MCMC(MCMC_results = AR_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, receptor = "Androgen", top = 20, iters = 200000)
AR_var_use

ER_var_use <- plot_variables_in_MCMC(MCMC_results = ER_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, receptor = "Estrogen", top = 20, iters = 200000)
ER_var_use
```


```{r plot_var_use_comparisons}

MCMC_var_use_comparisons <-plot_compare_vars_in_MCMC(MCMC_results_1 = AR_MCMC_results_main_outcome$MCMC_main_outcomes_analysis,
                          MCMC_results_2  = ER_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, 
                          receptor_1 = "Androgen", 
                          receptor_2 = "Estrogen", 
                          top = 20, 
                          iters = 200000)

MCMC_var_use_comparisons$top_receptor_1_agst_2
MCMC_var_use_comparisons$top_receptor_2_agst_1

```

```{r plot_var_use_comparisons_subgroups_of_receptor}

subgroup_plots <- plot_compare_vars_subgroups(AR_MCMC_results_subgroups)

subgroup_plots$`1`
```

```{r get_top_couples_and_triplets}
AR_MCMC_couples_triples <- extract_MCMC_couples_triples(AR_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, 
                                                        receptor = "Androgen", 
                                                        couple_thresh = 0.8, 
                                                        triple_thresh = 0.6)

ER_MCMC_couples_triples <- extract_MCMC_couples_triples(ER_MCMC_results_main_outcome$MCMC_main_outcomes_analysis, 
                                                     receptor = "Estrogen", 
                                                     couple_thresh = 0.8, 
                                                     triple_thresh = 0.6)

AR_ER_comparison_couples <- rbind(AR_MCMC_couples_triples$MCMC_couples, ER_MCMC_couples_triples$MCMC_couples)
AR_ER_comparison_triples <- rbind(AR_MCMC_couples_triples$MCMC_triples, ER_MCMC_couples_triples$MCMC_triples)

```

```{r extract_couples_triples_subgroups}

androgen_subgroups_couples_triples <- extract_MCMC_couples_triples_subgroups(MCMC_results = AR_MCMC_results_subgroups, 
                                                                            couple_thresh = 0.7, 
                                                                            triple_thresh = 0.5)

estrogen_subgroups_couples_triples <- extract_MCMC_couples_triples_subgroups(MCMC_results = ER_MCMC_results_subgroups, 
                                                                            couple_thresh = 0.7, 
                                                                            triple_thresh = 0.4)

```

```{r get mol tree variable}
mol_boolean_itx_results <- create_molecular_tree_var(MCMC_results = AR_MCMC_results_main_outcome$MCMC_main_outcomes_analysis,
                                      couple_thresh = 0.7,
                                      triple_thresh = 0.5,
                                      top_MCMC_vars_thresh = 0.8,
                                      binary_data = AR_data_PCs_grps,
                                      make_logic_tree = TRUE,
                                      expand_boolean_grid = FALSE,
                                      filter_type = "Pubchem",
                                      fingerprints = pubchem_fingerprints_cleaned,
                                      fingerprints_idx = 2,
                                      outcome_label = quo(Label_names),
                                      iters = 100) 

tree_formula <- mol_boolean_itx_results[[1]]$tree_formula
tree_var <- mol_boolean_itx_results[[1]]$tree_variable
accuracy <- mol_boolean_itx_results[[1]]$accuracy

subgroup_mol_boolean_itx_results <- map(.x = AR_logic_MCMC_results[2],
                                      .f=create_molecular_tree_var,
                                      MCMC_result,
                                      couple_thresh = 0.7,
                                      triple_thresh = 0.5,
                                      top_MCMC_vars_thresh = 0.8,
                                      binary_data = AR_data_PCs_grps,
                                      make_logic_tree = TRUE,
                                      expand_boolean_grid = FALSE,
                                      filter_type = "Pubchem",
                                      fingerprints = pubchem_fingerprints_cleaned,
                                      fingerprints_idx = 2,
                                      outcome_label = quo(log_SVM_group),
                                      iters = 100)

subgroup_mol_boolean_itx_results <- purrr::pmap(list(AR_MCMC_results_subgroups,
                                       AR_logic_MCMC_results$subgroup_outcomes,
                                       AR_logic_MCMC_results$subgroup_exposures,
                                       AR_logic_MCMC_results$subgroup_names),
                                      .f=create_molecular_tree_var,
                                      couple_thresh = 0,
                                      triple_thresh = 0,
                                      top_MCMC_vars_thresh = 0.4,
                                      binary_data = AR_data_PCs_grps,
                                      make_logic_tree = TRUE,
                                      expand_boolean_grid = FALSE,
                                      filter_type = "Pubchem",
                                      fingerprints = pubchem_fingerprints_cleaned,
                                      fingerprints_idx = 2,
                                      outcome_label = quo(log_SVM_group),
                                      iters = 100, 
                                      subgroup = TRUE)


```

```{r setup_python}
library(reticulate)
conda_list()
use_condaenv(condaenv = 'my-rdkit-env', required = TRUE)

```

```{python my-rdkit-env}
from rdkit import Chem
from rdkit import DataStructs

ms = [Chem.MolFromSmiles('CCOC'), Chem.MolFromSmiles('CCO'), Chem.MolFromSmiles('COC')]
fps = [Chem.RDKFingerprint(x) for x in ms]
DataStructs.FingerprintSimilarity(fps[0],fps[1])
DataStructs.FingerprintSimilarity(fps[0],fps[2])
DataStructs.FingerprintSimilarity(fps[1],fps[2])

fps
```




```{r combine_tree_var_with_physical_data}


for (i in 1:length(subgroup_mol_boolean_itx_results)) {
  formulas[i] <- subgroup_mol_boolean_itx_results[[i]][[1]]$tree_formula
}

AR_data_PCs_grps <- AR_data_PCs_grps %>%
    mutate(g1_mol_tree_var = ifelse(eval(parse(text = formulas[1])), 1, 0)) 

AR_data_PCs_grps <- AR_data_PCs_grps %>%
    mutate(g2_mol_tree_var = ifelse(eval(parse(text = formulas[2])), 1, 0)) 

AR_data_PCs_grps <- AR_data_PCs_grps %>%
    mutate(g3_mol_tree_var = ifelse(eval(parse(text = formulas[3])), 1, 0)) 

AR_data_PCs_grps <- AR_data_PCs_grps %>%
    mutate(g4_mol_tree_var = ifelse(eval(parse(text = formulas[4])), 1, 0)) 


#AR_data_PCs_grps_tree_var <- cbind(AR_data_PCs_grps, tree_var)

tree_var_w_names <- AR_data_PCs_grps %>% 
  select(Name, 
         g1_mol_tree_var, 
         g2_mol_tree_var, 
         g3_mol_tree_var, 
         g4_mol_tree_var,
         Label_names)


AR_data_PCs_grps_tree_var <- merge(AR_rdkit_descriptions, tree_var_w_names, 
                                   by.x = "NAME",
                                   by.y = "Name")

AR_data_PCs_grps_tree_var_cln <- AR_data_PCs_grps_tree_var %>% 
  select(-c(NAME,X,SMILES,LABEL,mol))

AR_data_PCs_grps_tree_var_cln$Label_names <- as.factor(AR_data_PCs_grps_tree_var_cln$Label_names)

mol_ens <- pre(Label_names ~ ., 
               data = AR_data_PCs_grps_tree_var_cln,
               family = binomial)

mol.cv <- cvpre(mol_ens)

predictions <- mol.cv$cvpreds
predictions_binary <- ifelse(predictions > 0.5, 1,0)

prediction_cm <- table(predictions_binary, AR_data_PCs_grps_tree_var_cln$Label_names)
confusionMatrix(prediction_cm)


plot(mol_ens, nterms = 2, cex = .5)

```
